# all directories in this file are located relative to the project root

[qroma.project]
id = "qroma-lights"
name = "qroma-lights"
# use semantic versioning - see https://en.wikipedia.org/wiki/Software_versioning [Semantic versioning]
version = "0.1.0"


[qroma.project.dirs]
pb_root = "{{ qroma_project_dir }}/protobufs"
firmware_root = "{{ qroma_project_dir }}/firmware/esp32/qroma-lights"
app_root = "{{ qroma_project_dir }}/apps/py-qroma-io"
site_root = "{{ qroma_project_dir }}/sites/site-www-qroma-lights"


[qroma.project.firmware]
platforms = [
  "platformio",
]


[qroma.project.run.commands.firmware.platformio]
build = "run"
install = "run --target upload --environment esp32dev"
monitor = ""

[qroma.project.stages.sw.protobuf]
root_dir = "{{ qroma.project_dirs.pb_root }}/protobufs"
compilers = [
  "nanopb",
  "python",
  "typescript",
  "dart",
]

[[qroma.project.stages.sw.protobuf.sources]]
source_path = "{{ qroma.project_dirs.pb_root }}/protofiles-in"
dest_path = "{{ qroma.project_dirs.pb_root }}/protofiles-out"


[qroma.project.stages.sw.protobuf.replication]
nanopb.dirs = ["{{ qroma.project_dirs.firmware_root }}/src/qroma-proto", ]
python.dirs = ["{{ qroma.project_dirs.app_root }}/qroma_proto", ]
typescript.dirs = ["{{ qroma.project_dirs.site_root }}/src/qroma-proto", ]
dart.dirs = []


[qroma.project.stages.sw.firmware]
project_dirs = []


[qroma.project.stages.sw.apps]
project_dirs = []


[qroma.project.stages.sw.sites]
project_dirs = []


[qroma.project.stages.sw.sites.bundle]
local_bundle_static_dir="{{ qroma.project_dirs.site_root }}/static"
local_bundle_static_qroma_dir="{{ qroma.project_dirs.site_root }}/static/qroma"
local_bundle_version_content_root_dir="{{ qroma.project_dirs.site_root }}/static/qroma/versions"
hosted_qroma_bundle_root="/qroma"
hosted_qroma_bundle_versions_root="/qroma/versions"
hosted_bundle_version_path="/qroma/versions/{{ qroma.project_version }}"


[[qroma.project.stages.sw.sites.bundle.publish_version.firmware_file_replications]]
source_filepath="{{ qroma.project_dirs.firmware_root }}/.pio/build/esp32dev/firmware.bin"
local_publication_filepath="{{ qroma.project_dirs.site_root }}/static/qroma/versions/{{ qroma.project_version }}/firmware/esp32dev/firmware.bin"
hosted_publication_filepath="/qroma/versions/{{ qroma.project_version }}/firmware/esp32dev/firmware.bin"


[[qroma.project.stages.sw.sites.bundle.publish_version.firmware_file_replications]]
source_filepath="{{ qroma.project_dirs.firmware_root }}/.pio/build/esp32dev/bootloader.bin"
local_publication_filepath="{{ qroma.project_dirs.site_root }}/static/qroma/versions/{{ qroma.project_version }}/firmware/esp32dev/bootloader.bin"
hosted_publication_filepath="/qroma/versions/{{ qroma.project_version }}/firmware/esp32dev/bootloader.bin"


[[qroma.project.stages.sw.sites.bundle.publish_version.firmware_file_replications]]
source_filepath="{{ qroma.project_dirs.firmware_root }}/.pio/build/esp32dev/partitions.bin"
local_publication_filepath="{{ qroma.project_dirs.site_root }}/static/qroma/versions/{{ qroma.project_version }}/firmware/esp32dev/partitions.bin"
hosted_publication_filepath="/qroma/versions/{{ qroma.project_version }}/firmware/esp32dev/partitions.bin"


[[qroma.project.stages.sw.sites.bundle.publish_version.firmware_file_replications]]
source_filepath="{{ qroma.user_profile_dirs.platform_io_packages_root }}/framework-arduinoespressif32/tools/partitions/boot_app0.bin"
local_publication_filepath="{{ qroma.project_dirs.site_root }}/static/qroma/versions/{{ qroma.project_version }}/firmware/esp32dev/boot_app0.bin"
hosted_publication_filepath="/qroma/versions/{{ qroma.project_version }}/firmware/esp32dev/boot_app0.bin"


[[qroma.project.stages.sw.sites.bundle.publish_version.firmware_file_replications]]
source_filepath="{{ qroma.project_dirs.firmware_root }}/.pio/build/adafruit_qtpy_esp32c3/firmware.bin"
local_publication_filepath="{{ qroma.project_dirs.site_root }}/static/qroma/versions/{{ qroma.project_version }}/firmware/adafruit_qtpy_esp32c3/firmware.bin"
hosted_publication_filepath="/qroma/versions/{{ qroma.project_version }}/firmware/adafruit_qtpy_esp32c3/firmware.bin"


[[qroma.project.stages.sw.sites.bundle.publish_version.firmware_file_replications]]
source_filepath="{{ qroma.project_dirs.firmware_root }}/.pio/build/adafruit_qtpy_esp32c3/bootloader.bin"
local_publication_filepath="{{ qroma.project_dirs.site_root }}/static/qroma/versions/{{ qroma.project_version }}/firmware/adafruit_qtpy_esp32c3/bootloader.bin"
hosted_publication_filepath="/qroma/versions/{{ qroma.project_version }}/firmware/adafruit_qtpy_esp32c3/bootloader.bin"


[[qroma.project.stages.sw.sites.bundle.publish_version.firmware_file_replications]]
source_filepath="{{ qroma.project_dirs.firmware_root }}/.pio/build/adafruit_qtpy_esp32c3/partitions.bin"
local_publication_filepath="{{ qroma.project_dirs.site_root }}/static/qroma/versions/{{ qroma.project_version }}/firmware/adafruit_qtpy_esp32c3/partitions.bin"
hosted_publication_filepath="/qroma/versions/{{ qroma.project_version }}/firmware/adafruit_qtpy_esp32c3/partitions.bin"


[[qroma.project.stages.sw.sites.bundle.publish_version.firmware_file_replications]]
source_filepath="{{ qroma.user_profile_dirs.platform_io_packages_root }}/framework-arduinoespressif32/tools/partitions/boot_app0.bin"
local_publication_filepath="{{ qroma.project_dirs.site_root }}/static/qroma/versions/{{ qroma.project_version }}/firmware/adafruit_qtpy_esp32c3/boot_app0.bin"
hosted_publication_filepath="/qroma/versions/{{ qroma.project_version }}/firmware/adafruit_qtpy_esp32c3/boot_app0.bin"


[[qroma.project.stages.sw.sites.bundle.publish_version.zipped_dirs]]
source_dir="{{ qroma.project_dirs.pb_root }}/protofiles-out"
local_publication_zip_file="{{ qroma.project_dirs.site_root }}/static/qroma/versions/{{ qroma.project_version }}/protobufs.zip"


[[qroma.project.stages.sw.sites.bundle.publish_version.generated_files]]
local_publication_filepath="{{ qroma.project_dirs.site_root }}/static/qroma/versions/{{ qroma.project_version }}/firmware/manifest-firmware.json"
hosted_publication_filepath="/qroma/versions/{{ qroma.project_version }}/firmware/manifest-firmware.json"
template_str="""{
  "name": "qroma-lights",
  "version": "esp32",
  "builds": [
    {
      "chipFamily": "ESP32",
      "parts": [
        { "path": "esp32dev/bootloader.bin", "offset": 4096 },
        { "path": "esp32dev/partitions.bin", "offset": 32768 },
        { "path": "esp32dev/boot_app0.bin", "offset": 57344 },
        { "path": "esp32dev/firmware.bin", "offset": 65536 }
      ]
    },
    {
      "chipFamily": "ESP32-C3",
      "parts": [
        { "path": "adafruit_qtpy_esp32c3/bootloader.bin", "offset": 0 },
        { "path": "adafruit_qtpy_esp32c3/partitions.bin", "offset": 32768 },
        { "path": "adafruit_qtpy_esp32c3/boot_app0.bin", "offset": 57344 },
        { "path": "adafruit_qtpy_esp32c3/firmware.bin", "offset": 65536 }
      ]
    }
  ]
}
"""