/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "qroma-lights-types.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(QromaStripColor, QromaStripColor, AUTO)


PB_BIND(QromaStrip_WS2812FX_Animation, QromaStrip_WS2812FX_Animation, AUTO)


PB_BIND(QromaStrip_WS2812FX_IoSettings, QromaStrip_WS2812FX_IoSettings, AUTO)


PB_BIND(QromaStrip_WS2812FX_Segment, QromaStrip_WS2812FX_Segment, AUTO)


PB_BIND(QromaStrip_WS2812FX_SegmentsDefinition, QromaStrip_WS2812FX_SegmentsDefinition, AUTO)


PB_BIND(QromaStrip_WS2812FX_StartupAnimations, QromaStrip_WS2812FX_StartupAnimations, 2)


PB_BIND(QromaStripConfig, QromaStripConfig, 2)


PB_BIND(QromaLightsConfig, QromaLightsConfig, 2)









