/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_QROMA_STRIP_COMMAND_PB_H_INCLUDED
#define PB_QROMA_STRIP_COMMAND_PB_H_INCLUDED
#include <pb.h>
#include "qroma-lights-types.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _QromaStripResponse { 
    char dummy_field;
} QromaStripResponse;

typedef struct _QromaStrip_Status { 
    uint32_t lastConfigChangeTimeInMs; 
} QromaStrip_Status;

typedef struct _SaveQromaStrip_CurrentState { 
    QromaStrip_WS2812FX_StripIndex stripIndex; 
} SaveQromaStrip_CurrentState;

typedef struct _SetQromaStrip_WS2812FX_Brightness { 
    QromaStrip_WS2812FX_StripIndex stripIndex; 
    uint32_t brightness; /* 0-255 */
} SetQromaStrip_WS2812FX_Brightness;

typedef struct _SetQromaStrip_WS2812FX_IoSettings { 
    QromaStrip_WS2812FX_StripIndex stripIndex; 
    bool has_settings;
    QromaStrip_WS2812FX_IoSettings settings; 
} SetQromaStrip_WS2812FX_IoSettings;

typedef struct _SetQromaStrip_WS2812FX_SegmentAnimation { 
    bool has_animation;
    QromaStrip_WS2812FX_Animation animation; 
    QromaStrip_WS2812FX_StripIndex stripIndex; 
    uint32_t segmentIndex; 
} SetQromaStrip_WS2812FX_SegmentAnimation;

typedef struct _SetQromaStrip_WS2812FX_Segments { 
    QromaStrip_WS2812FX_StripIndex stripIndex; 
    uint32_t numSegments; 
    QromaStrip_WS2812FX_Segment segments[5]; /* repeated QromaStrip_WS2812FX_Animation animations = 4; */
} SetQromaStrip_WS2812FX_Segments;

typedef struct _QromaStripCommand { 
    pb_size_t which_command;
    union {
        SetQromaStrip_WS2812FX_Brightness setQromaStripBrightness;
        SetQromaStrip_WS2812FX_SegmentAnimation setQromaStripSegmentAnimation;
        SetQromaStrip_WS2812FX_Segments setQromaStripSegments;
        SetQromaStrip_WS2812FX_IoSettings setQromaStripIoSettings;
        SaveQromaStrip_CurrentState saveQromaStripCurrentState;
    } command; 
} QromaStripCommand;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define SetQromaStrip_WS2812FX_Segments_init_default {_QromaStrip_WS2812FX_StripIndex_MIN, 0, {QromaStrip_WS2812FX_Segment_init_default, QromaStrip_WS2812FX_Segment_init_default, QromaStrip_WS2812FX_Segment_init_default, QromaStrip_WS2812FX_Segment_init_default, QromaStrip_WS2812FX_Segment_init_default}}
#define SetQromaStrip_WS2812FX_SegmentAnimation_init_default {false, QromaStrip_WS2812FX_Animation_init_default, _QromaStrip_WS2812FX_StripIndex_MIN, 0}
#define SetQromaStrip_WS2812FX_Brightness_init_default {_QromaStrip_WS2812FX_StripIndex_MIN, 0}
#define SetQromaStrip_WS2812FX_IoSettings_init_default {_QromaStrip_WS2812FX_StripIndex_MIN, false, QromaStrip_WS2812FX_IoSettings_init_default}
#define SaveQromaStrip_CurrentState_init_default {_QromaStrip_WS2812FX_StripIndex_MIN}
#define QromaStripCommand_init_default           {0, {SetQromaStrip_WS2812FX_Brightness_init_default}}
#define QromaStripResponse_init_default          {0}
#define QromaStrip_Status_init_default           {0}
#define SetQromaStrip_WS2812FX_Segments_init_zero {_QromaStrip_WS2812FX_StripIndex_MIN, 0, {QromaStrip_WS2812FX_Segment_init_zero, QromaStrip_WS2812FX_Segment_init_zero, QromaStrip_WS2812FX_Segment_init_zero, QromaStrip_WS2812FX_Segment_init_zero, QromaStrip_WS2812FX_Segment_init_zero}}
#define SetQromaStrip_WS2812FX_SegmentAnimation_init_zero {false, QromaStrip_WS2812FX_Animation_init_zero, _QromaStrip_WS2812FX_StripIndex_MIN, 0}
#define SetQromaStrip_WS2812FX_Brightness_init_zero {_QromaStrip_WS2812FX_StripIndex_MIN, 0}
#define SetQromaStrip_WS2812FX_IoSettings_init_zero {_QromaStrip_WS2812FX_StripIndex_MIN, false, QromaStrip_WS2812FX_IoSettings_init_zero}
#define SaveQromaStrip_CurrentState_init_zero    {_QromaStrip_WS2812FX_StripIndex_MIN}
#define QromaStripCommand_init_zero              {0, {SetQromaStrip_WS2812FX_Brightness_init_zero}}
#define QromaStripResponse_init_zero             {0}
#define QromaStrip_Status_init_zero              {0}

/* Field tags (for use in manual encoding/decoding) */
#define QromaStrip_Status_lastConfigChangeTimeInMs_tag 1
#define SaveQromaStrip_CurrentState_stripIndex_tag 1
#define SetQromaStrip_WS2812FX_Brightness_stripIndex_tag 1
#define SetQromaStrip_WS2812FX_Brightness_brightness_tag 2
#define SetQromaStrip_WS2812FX_IoSettings_stripIndex_tag 1
#define SetQromaStrip_WS2812FX_IoSettings_settings_tag 2
#define SetQromaStrip_WS2812FX_SegmentAnimation_animation_tag 1
#define SetQromaStrip_WS2812FX_SegmentAnimation_stripIndex_tag 2
#define SetQromaStrip_WS2812FX_SegmentAnimation_segmentIndex_tag 3
#define SetQromaStrip_WS2812FX_Segments_stripIndex_tag 1
#define SetQromaStrip_WS2812FX_Segments_numSegments_tag 2
#define SetQromaStrip_WS2812FX_Segments_segments_tag 3
#define QromaStripCommand_setQromaStripBrightness_tag 1
#define QromaStripCommand_setQromaStripSegmentAnimation_tag 2
#define QromaStripCommand_setQromaStripSegments_tag 3
#define QromaStripCommand_setQromaStripIoSettings_tag 4
#define QromaStripCommand_saveQromaStripCurrentState_tag 5

/* Struct field encoding specification for nanopb */
#define SetQromaStrip_WS2812FX_Segments_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    stripIndex,        1) \
X(a, STATIC,   SINGULAR, UINT32,   numSegments,       2) \
X(a, STATIC,   FIXARRAY, MESSAGE,  segments,          3)
#define SetQromaStrip_WS2812FX_Segments_CALLBACK NULL
#define SetQromaStrip_WS2812FX_Segments_DEFAULT NULL
#define SetQromaStrip_WS2812FX_Segments_segments_MSGTYPE QromaStrip_WS2812FX_Segment

#define SetQromaStrip_WS2812FX_SegmentAnimation_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  animation,         1) \
X(a, STATIC,   SINGULAR, UENUM,    stripIndex,        2) \
X(a, STATIC,   SINGULAR, UINT32,   segmentIndex,      3)
#define SetQromaStrip_WS2812FX_SegmentAnimation_CALLBACK NULL
#define SetQromaStrip_WS2812FX_SegmentAnimation_DEFAULT NULL
#define SetQromaStrip_WS2812FX_SegmentAnimation_animation_MSGTYPE QromaStrip_WS2812FX_Animation

#define SetQromaStrip_WS2812FX_Brightness_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    stripIndex,        1) \
X(a, STATIC,   SINGULAR, UINT32,   brightness,        2)
#define SetQromaStrip_WS2812FX_Brightness_CALLBACK NULL
#define SetQromaStrip_WS2812FX_Brightness_DEFAULT NULL

#define SetQromaStrip_WS2812FX_IoSettings_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    stripIndex,        1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  settings,          2)
#define SetQromaStrip_WS2812FX_IoSettings_CALLBACK NULL
#define SetQromaStrip_WS2812FX_IoSettings_DEFAULT NULL
#define SetQromaStrip_WS2812FX_IoSettings_settings_MSGTYPE QromaStrip_WS2812FX_IoSettings

#define SaveQromaStrip_CurrentState_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    stripIndex,        1)
#define SaveQromaStrip_CurrentState_CALLBACK NULL
#define SaveQromaStrip_CurrentState_DEFAULT NULL

#define QromaStripCommand_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,setQromaStripBrightness,command.setQromaStripBrightness),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,setQromaStripSegmentAnimation,command.setQromaStripSegmentAnimation),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,setQromaStripSegments,command.setQromaStripSegments),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,setQromaStripIoSettings,command.setQromaStripIoSettings),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,saveQromaStripCurrentState,command.saveQromaStripCurrentState),   5)
#define QromaStripCommand_CALLBACK NULL
#define QromaStripCommand_DEFAULT NULL
#define QromaStripCommand_command_setQromaStripBrightness_MSGTYPE SetQromaStrip_WS2812FX_Brightness
#define QromaStripCommand_command_setQromaStripSegmentAnimation_MSGTYPE SetQromaStrip_WS2812FX_SegmentAnimation
#define QromaStripCommand_command_setQromaStripSegments_MSGTYPE SetQromaStrip_WS2812FX_Segments
#define QromaStripCommand_command_setQromaStripIoSettings_MSGTYPE SetQromaStrip_WS2812FX_IoSettings
#define QromaStripCommand_command_saveQromaStripCurrentState_MSGTYPE SaveQromaStrip_CurrentState

#define QromaStripResponse_FIELDLIST(X, a) \

#define QromaStripResponse_CALLBACK NULL
#define QromaStripResponse_DEFAULT NULL

#define QromaStrip_Status_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   lastConfigChangeTimeInMs,   1)
#define QromaStrip_Status_CALLBACK NULL
#define QromaStrip_Status_DEFAULT NULL

extern const pb_msgdesc_t SetQromaStrip_WS2812FX_Segments_msg;
extern const pb_msgdesc_t SetQromaStrip_WS2812FX_SegmentAnimation_msg;
extern const pb_msgdesc_t SetQromaStrip_WS2812FX_Brightness_msg;
extern const pb_msgdesc_t SetQromaStrip_WS2812FX_IoSettings_msg;
extern const pb_msgdesc_t SaveQromaStrip_CurrentState_msg;
extern const pb_msgdesc_t QromaStripCommand_msg;
extern const pb_msgdesc_t QromaStripResponse_msg;
extern const pb_msgdesc_t QromaStrip_Status_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define SetQromaStrip_WS2812FX_Segments_fields &SetQromaStrip_WS2812FX_Segments_msg
#define SetQromaStrip_WS2812FX_SegmentAnimation_fields &SetQromaStrip_WS2812FX_SegmentAnimation_msg
#define SetQromaStrip_WS2812FX_Brightness_fields &SetQromaStrip_WS2812FX_Brightness_msg
#define SetQromaStrip_WS2812FX_IoSettings_fields &SetQromaStrip_WS2812FX_IoSettings_msg
#define SaveQromaStrip_CurrentState_fields &SaveQromaStrip_CurrentState_msg
#define QromaStripCommand_fields &QromaStripCommand_msg
#define QromaStripResponse_fields &QromaStripResponse_msg
#define QromaStrip_Status_fields &QromaStrip_Status_msg

/* Maximum encoded size of messages (where known) */
#define QromaStripCommand_size                   88
#define QromaStripResponse_size                  0
#define QromaStrip_Status_size                   6
#define SaveQromaStrip_CurrentState_size         2
#define SetQromaStrip_WS2812FX_Brightness_size   8
#define SetQromaStrip_WS2812FX_IoSettings_size   20
#define SetQromaStrip_WS2812FX_SegmentAnimation_size 86
#define SetQromaStrip_WS2812FX_Segments_size     78

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
