/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_QROMA_LIGHTS_COMMAND_PB_H_INCLUDED
#define PB_QROMA_LIGHTS_COMMAND_PB_H_INCLUDED
#include <pb.h>
#include "qroma-lights-types.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* not sure how I feel about this, but let's try it out, at least */
typedef enum _NoArgCommands_QromaLightsCommand { 
    NoArgCommands_QromaLightsCommand_NacQlc_NotSet = 0, 
    NoArgCommands_QromaLightsCommand_NacQlc_UseCurrentSetupOnStartup = 1, 
    NoArgCommands_QromaLightsCommand_NacQlc_RestartQromaDevice = 2, 
    NoArgCommands_QromaLightsCommand_NacQlc_FactoryResetQromaDevice = 3, 
    NoArgCommands_QromaLightsCommand_NacQlc_RequestQromaLightsConfig = 4 
} NoArgCommands_QromaLightsCommand;

/* Struct definitions */
typedef struct _QpmCommand_SetQromaStripName { 
    char name[30]; 
} QpmCommand_SetQromaStripName;

typedef struct _QromaLightsResponse { 
    pb_size_t which_response;
    union {
        QromaLightsConfig qromaLightsConfigResponse;
    } response; 
} QromaLightsResponse;

typedef struct _SetQromaStripDeviceName { 
    char name[30]; 
} SetQromaStripDeviceName;

typedef struct _UseCurrentSetupOnStartup { 
    uint32_t delayInMs; 
} UseCurrentSetupOnStartup;

typedef struct _QromaLightsCommand { 
    pb_size_t which_command;
    union {
        NoArgCommands_QromaLightsCommand noArgCommand;
        SetQromaStripDeviceName setQromaStripDeviceName;
    } command; 
} QromaLightsCommand;


/* Helper constants for enums */
#define _NoArgCommands_QromaLightsCommand_MIN NoArgCommands_QromaLightsCommand_NacQlc_NotSet
#define _NoArgCommands_QromaLightsCommand_MAX NoArgCommands_QromaLightsCommand_NacQlc_RequestQromaLightsConfig
#define _NoArgCommands_QromaLightsCommand_ARRAYSIZE ((NoArgCommands_QromaLightsCommand)(NoArgCommands_QromaLightsCommand_NacQlc_RequestQromaLightsConfig+1))


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define QpmCommand_SetQromaStripName_init_default {""}
#define SetQromaStripDeviceName_init_default     {""}
#define UseCurrentSetupOnStartup_init_default    {0}
#define QromaLightsCommand_init_default          {0, {_NoArgCommands_QromaLightsCommand_MIN}}
#define QromaLightsResponse_init_default         {0, {QromaLightsConfig_init_default}}
#define QpmCommand_SetQromaStripName_init_zero   {""}
#define SetQromaStripDeviceName_init_zero        {""}
#define UseCurrentSetupOnStartup_init_zero       {0}
#define QromaLightsCommand_init_zero             {0, {_NoArgCommands_QromaLightsCommand_MIN}}
#define QromaLightsResponse_init_zero            {0, {QromaLightsConfig_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define QpmCommand_SetQromaStripName_name_tag    1
#define QromaLightsResponse_qromaLightsConfigResponse_tag 1
#define SetQromaStripDeviceName_name_tag         1
#define UseCurrentSetupOnStartup_delayInMs_tag   1
#define QromaLightsCommand_noArgCommand_tag      1
#define QromaLightsCommand_setQromaStripDeviceName_tag 2

/* Struct field encoding specification for nanopb */
#define QpmCommand_SetQromaStripName_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   name,              1)
#define QpmCommand_SetQromaStripName_CALLBACK NULL
#define QpmCommand_SetQromaStripName_DEFAULT NULL

#define SetQromaStripDeviceName_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   name,              1)
#define SetQromaStripDeviceName_CALLBACK NULL
#define SetQromaStripDeviceName_DEFAULT NULL

#define UseCurrentSetupOnStartup_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   delayInMs,         1)
#define UseCurrentSetupOnStartup_CALLBACK NULL
#define UseCurrentSetupOnStartup_DEFAULT NULL

#define QromaLightsCommand_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    UENUM,    (command,noArgCommand,command.noArgCommand),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,setQromaStripDeviceName,command.setQromaStripDeviceName),   2)
#define QromaLightsCommand_CALLBACK NULL
#define QromaLightsCommand_DEFAULT NULL
#define QromaLightsCommand_command_setQromaStripDeviceName_MSGTYPE SetQromaStripDeviceName

#define QromaLightsResponse_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,qromaLightsConfigResponse,response.qromaLightsConfigResponse),   1)
#define QromaLightsResponse_CALLBACK NULL
#define QromaLightsResponse_DEFAULT NULL
#define QromaLightsResponse_response_qromaLightsConfigResponse_MSGTYPE QromaLightsConfig

extern const pb_msgdesc_t QpmCommand_SetQromaStripName_msg;
extern const pb_msgdesc_t SetQromaStripDeviceName_msg;
extern const pb_msgdesc_t UseCurrentSetupOnStartup_msg;
extern const pb_msgdesc_t QromaLightsCommand_msg;
extern const pb_msgdesc_t QromaLightsResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define QpmCommand_SetQromaStripName_fields &QpmCommand_SetQromaStripName_msg
#define SetQromaStripDeviceName_fields &SetQromaStripDeviceName_msg
#define UseCurrentSetupOnStartup_fields &UseCurrentSetupOnStartup_msg
#define QromaLightsCommand_fields &QromaLightsCommand_msg
#define QromaLightsResponse_fields &QromaLightsResponse_msg

/* Maximum encoded size of messages (where known) */
#define QpmCommand_SetQromaStripName_size        31
#define QromaLightsCommand_size                  33
#define QromaLightsResponse_size                 1085
#define SetQromaStripDeviceName_size             31
#define UseCurrentSetupOnStartup_size            6

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
