/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "qroma-strip-command.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(SetQromaStrip_WS2812FX_Segments, SetQromaStrip_WS2812FX_Segments, AUTO)


PB_BIND(SetQromaStrip_WS2812FX_SegmentAnimation, SetQromaStrip_WS2812FX_SegmentAnimation, AUTO)


PB_BIND(SetQromaStrip_WS2812FX_Brightness, SetQromaStrip_WS2812FX_Brightness, AUTO)


PB_BIND(SetQromaStrip_WS2812FX_IoSettings, SetQromaStrip_WS2812FX_IoSettings, AUTO)


PB_BIND(SaveQromaStrip_CurrentState, SaveQromaStrip_CurrentState, AUTO)


PB_BIND(QromaStripCommand, QromaStripCommand, AUTO)


PB_BIND(QromaStripResponse, QromaStripResponse, AUTO)


PB_BIND(QromaStrip_Status, QromaStrip_Status, AUTO)



