/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "qroma-lights-command.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(QpmCommand_SetQromaStripName, QpmCommand_SetQromaStripName, AUTO)


PB_BIND(SetQromaStripDeviceName, SetQromaStripDeviceName, AUTO)


PB_BIND(UseCurrentSetupOnStartup, UseCurrentSetupOnStartup, AUTO)


PB_BIND(QromaLightsCommand, QromaLightsCommand, AUTO)


PB_BIND(QromaLightsResponse, QromaLightsResponse, 2)




